os: Visual Studio 2019

environment:
    PYTHON: "C:\\Python37"

    matrix:
        - PROFILE:  msvc-d-shared
        - PROFILE:  msvc-r-static
install:
  - git submodule update --init
  - ci\cpp\conan\appveyor\install.bat

build_script:
  - ci\cpp\conan\appveyor\run.bat %PROFILE%
