os: Visual Studio 2019

environment:
    PYTHON: "C:\Python37"

    matrix:

        - PROFILE:  msvc-d-shared
        - PROFILE:  msvc-r-static

install:
  - git clone https://github.com/TimSimpson/ci-land.git ci
  - cd ci
  - git checkout 3f0e77a79836a194ec2e5745341919bd6b9cc2c1
  - cd ..
  - ci\cpp\conan\appveyor\install.bat

build_script:
  - ci\cpp\conan\appveyor\run.bat %PROFILE%
