os: Visual Studio 2019

environment:
    PYTHON: "C:\\Python37"

    matrix:
        - PROFILE:  msvc-d-shared
        - PROFILE:  msvc-r-static
install:
  - ci\appveyor\install.bat

build_script:
  - ci\appveyor\run.bat %PROFILE%
